
# 結 {.unnumbered}{#sec-conc}

## 本論文の成果

本論文では文化の保存と継承を目指す視点から記録の重要性を指摘し，具体的な対象として日本の伝統音楽である雅楽を取り上げながら，デジタル技術を用いた音楽情報の機械可読な表現による無形文化の保存と継承の可能性について議論を行ってきた．長い伝統と歴史を持つ日本の音楽文化は現在に至るまで人から人へと口伝によって継承されてきた歴史を持つが，近年では後継者不足，上演機会の減少，実演を支えるインフラの弱体化など，その継承環境は厳しさを増している．また，物理的な資料は常に消失のリスクを抱えており，それを最小限にとどめることを目的として，より安定した環境での保管を実施した結果，資料のアクセスに対するハードルが上がるという，保存と公開のジレンマに文化財保護は長らく悩まされてきた．

文化財のデジタル化はこのような問題に対する解決策の1つとして注目され，博物館，図書館，文書館が所蔵する資料のデジタルアーカイブ化，博物館法における電子的記録の作成と公開の明文化など，文化資料のデジタル化に向けた取り組みは複数の側面から同時に進行しつつある．
電子的複製物の公開によって当該資料への幅広いアクセスを実現すると同時に，実物資料をよりリスクの低い環境で保管することが可能になり，資料の保存と公開の両立を図ることができる資料のデジタル化は今後も一層進展していくことが予想される．

本研究が展開してきたデジタル雅楽譜に向けた議論は，デジタル画像として公開された楽譜資料を典拠としつつ，機械可読な方法で雅楽譜の記述内容をマークアップするとともに，それを1つの軸とした雅楽情報のネットワーク化を見据えたものであった．それは，デジタル画像として公開された資料のより柔軟な利用を可能にするために，資料が持つコンテンツを機械可読な形式で記述する方法を提供すると同時に，インターネット上に溢れる大量の関連情報を必要に応じて繋ぎ合わせ，新たな知識を生み出していく情報表現の基礎となることを目指すものである．

音楽とコンピュータの間で築かれてきた緊密な関係性の下，音楽関連資料の機械可読化は多様なニーズと目的によって目指されてきたが，その多くが西洋音楽の用いる音楽理論と五線譜による音楽記述体系を基盤としており，日本の伝統音楽をはじめ，非西洋音楽を対象とした音楽資料はその特殊性から機械可読化に向けた取り組みが全体的な傾向として遅れている状況にある．また，西洋音楽を対象に展開されてきた既存の音楽記述枠組みを用いて日本伝統音楽が用いる楽譜資料のデジタル化に取り組んだ過去の事例は，楽譜印刷データの作成というユーザーのニーズを一定程度満たすことに成功した一方で，そのデータはあくまでも人間が読んで理解することを前提とする印刷楽譜版面をコンピュータ上で構成することを目的とするものであり，楽譜資料が持つ情報の構造的な記述を想定したものではなかった．

本論文による第一の貢献として，このような西洋中心的傾向にある音楽情報記述環境に対して，非西洋音楽である雅楽譜を対象とした音楽情報記述モデルを提示したことが挙げられる．
デジタル画像として公開されている資料の翻刻によって，その資料が持つ情報がより柔軟に利用可能な状況がもたらされることは，OpenLibrary，HathiTrust，国立国会図書館デジタルコレクション，みんなで翻刻など，既存のプロジェクトによって既に十分実証されている．しかし，それを実現するためには翻刻および構造化の対象となる資料が持つ情報の特徴を十分に反映した適切な情報記述モデルとそれに基づいた具体的なデータ記述スキーマが求められる．本論文が議論してきた雅楽情報記述モデルと半構造化譜字ユニットおよびメタデータのスキーマを用いることで，急速に進むデジタル画像による資料の公開によってアクセス可能になった情報を機械可読に翻刻する手段がもたらされ，デジタル画像資料の活用可能性が一層広がっていくことが期待できる．

また，より広い文脈においては，物理的な形態をとる実物資料をデジタルデータとして記録していくことが，その記録の対象となった具体的な``もの''のみならず，その背後に存在する無形文化財である人間の文化的営みを保護，継承していく活動として位置付けられることを示した．これは文化財保護の文脈に本論文をどのように位置付けるかという問題とも密接に関わっている．本論文のような情報技術を用いた文化の記録は，文化財保護における既存の取り組みを新しい技術の導入によって単に置き換えていくというだけでなく，それ自体が有形・無形の文化財の保護と継承に資するものであり，現存資料の保存，管理，修復等の取り組みと同様の水準で取り組まれるべき存在であるといえる．

## 課題と展望

デジタル雅楽譜の構築において，本論文に残された第一の課題は\ref{chap:XML}章末で述べたとおり，雅楽情報記述モデルにおけるファクシミリ領域，時系列メディア領域の具体的な記述について検討を進め，本研究の成果である半構造化ユニットをさらに拡張していくことである．IIIF画像との連携については，MEIにおいてもベストプラクティスと呼びうる取り組みが複数並列して展開している状況にあり，その具体的な記述手法について西洋音楽における取り組みも参照しつつ検討していくことが求められる．また，時系列メディアの統合については，博士論文提出後の研究課題として，映像や音源といった複数の演奏記録に対してDynamic Time WarpingやHarmonic-Percussive Separationと呼ばれる技術を用いたアライメントを実施し，その結果を本論文において構築した半構造化譜字ユニットの記述と統合させることを計画している．
楽譜，楽書，楽師個人の記述など，雅楽文化の内側からもたらされる主観的な情報と，雅楽を外側から客観的に捉えた情報の接続は，より詳細な楽曲の構造や演奏の特徴を研究の主題として俎上に載せるための重要なステップである．

また，デジタル雅楽譜の拡張と合わせて，構造化されたデータの記述内容を確認するための楽譜表示インターフェイスの開発も課題として挙げられる．研究を目的としたデータの構築を目指す上では，ユーザビリティの追求は必ずしも求められるものではないが，構築したデータを公開し，より広く使用してもらうためには，楽譜とそれに関わる情報を分かりやすく表示する手段が求められる．また，楽譜表示のインターフェイスは入力内容の確認手段としても有効と考えられ，適切な可視化によってデータ品質が向上すれば，楽譜データに対する信頼向上にも繋がるだろう．

さらに，研究のスケーラビリティを高めるためには，雅楽の残した膨大な資料のさらなる翻刻とマークアップをどのように実現するかという問題にも向き合う必要がある．1つの可能性としては雅楽譜を対象としたOMRの開発が挙げられるが，楽譜の記述が多様であり，レパートリーが限られ，新曲が基本的に存在しない音楽文化を対象としたOMRの開発にかかるコストの回収には困難も予想される．また，みんなで翻刻のように，複数人による協働によって翻刻を進めるアプローチも考えられるが，その場合は，翻刻の品質を保つための品質管理スキームと楽譜入力インターフェイスの開発に取り組む必要があるだろう．GUIを搭載した雅楽譜版WYSIWYGエディタが登場すれば，雅楽譜翻刻のクラウドソーシングも実現不可能ではないかもしれないが，その場合にはOpenScoreが経験したような視覚的正しさと構造的正しさの隔たりを回避するための具体的な方策を用意して挑む必要がある．

最後に，本論文内では一切触れることはできなかったが，非西洋音楽の構造記述データを用いた機械学習技術との連携も大きな可能性のある領域である．既存の音楽データの大きな偏りによって，音楽に関わる昨今のAI研究はもっぱら西洋音楽を軸に展開されている．非西洋音楽が持つ構造が反映されたデータをAI研究に用いることでAIが音楽として扱いうる情報の幅が広がれば，より多様な音楽文化を対象とした音楽情報処理技術の発展に貢献する可能性がある．MIRや音楽符号化の議論において非西洋音楽研究に対して課せられてきた参入障壁は，音楽を対象として急速に展開されている世界的なAI利用の状況においても依然として立ちはだかっている．本論文を1つの足掛かりとしつつ，音楽文化が育んできた文化的多様性の実態をより正確に反映した音楽とコンピュータの関係性を目指し，引き続きこれらの問題に取り組んでいく必要がある．

音楽という無形の文化を対象とした機械可読化は万能ではなく，常に一定の限界が存在している．楽譜に記述された要素が機械可読に表現されたとしても，音楽文化そのものが完全に記録されるわけではない．音楽文化を構成する情報の中には，身体的な感覚，演奏環境によってもたらされるアフォーダンス，予め共有された経験を前提とした非言語的コミュニケーションなど，記号やデータでは表現しきれない要素が多分に含まれている．本論文の議論はそれを踏まえた上で，なお記録というアプローチから文化の保存や継承を議論するものであり，決して人間を介さない文化伝承を訴求するものではない．音楽文化の多様性や豊かさは，あくまで人間の経験や感覚を通してもたらされるものである．技術によってもたらされる新規性や可能性を過信せずに，常に文化そのものと向き合いながら，情報技術と文化の交流によってもたらされる，より豊かな文化的環境を目指して模索を続けていくことが求められる．

