# 序


音楽文化の持つ長い歴史は、その伝承に対する先人たちのたゆまぬ努力によって紡がれてきた。現在を生きる私たちはその伝承の先頭に立たされ、過去の伝承を受け継ぎながら未来への伝承について向き合うことを迫られる。これは音楽に限らず人間生活が生み出した文化にあまねく当てはまることだが、その困難さは伝承の対象となる文化が置かれた状況によって大きく異なる。継承を意識して取り組むまでもなく実践知として世代を越えた伝承がなされていく文化があるのに対して、能動的に保護を働きかけていかなければ伝承が途絶えかねない文化も存在する。文化が絶えず変化していくことは確かだが、その変化の帰結として文化の喪失を許容するような適者生存の理論を文化の保存や伝承に適用することがあってはならない。一方で、残念ながら失われていく文化の存在は否定できない事実である。したがって、私たちは守るべきものを守る手立てを講じると同時に、失われゆくものを記録するという2つの作業を同時に展開することを求められている。

## 日本伝統音楽の継承における理想と現状


音楽の保存について究極的な理想を打ち立てるのであれば、音楽行為のプロセスにおいて生み出された様々なドキュメントを適切に維持管理しながら、人間をメディアとして伝承されることが最も望ましいだろう。しかし、このような理想は多くの伝統音楽文化が置かれた実際の状況とは程遠い。事実、音楽文化の保存と継承には大きな課題を抱えている。少々古い調査だが、日本芸能実演家団体協議会による『伝統芸能の現場調査』
    ^[本調査における邦楽の対象ジャンルは、雅楽、声明、三曲（地歌・箏曲、尺八、胡弓楽）、義太夫、長唄（鳴物を含む）、常磐津、清元、新内、古曲（荻江節、一中節、河東節、宮薗節）、端唄・小唄、民謡、琵琶（平曲、筑前琵琶、薩摩琵琶ほか）、浪曲、能・狂言、邦楽ジョイント（邦楽の複数ジャンルによる演奏会）、他分野とのジョイント、その他。]
によると、調査の対象となった邦楽、邦舞、能楽、演芸、歌舞伎、文楽のうち、「後継者の先細りはしていない」と評価されたのは演芸（落語）のみであり、歌舞伎・文楽・演芸・能楽・邦楽・邦舞については、「中堅・ベテランの死亡、若い世代の不足」が指摘されている[@日本芸能実演家団体協議会伝統文化振興部2008, 109]。また、歌舞伎・文楽・演芸・能楽・邦楽・邦舞は「道具・楽器等の維持・管理も重い負担、それらに使われる材料と作る職人の技術の伝承後継者とも不足」[@日本芸能実演家団体協議会伝統文化振興部2008, 109]と指摘されている。さらに、邦楽・邦舞については、「公演に適したホールが、ここ10年ほどの間に相次いで閉鎖」、「専用劇場はなく、特別な育成事業は行われていない」[@日本芸能実演家団体協議会伝統文化振興部2008, p.108]とも指摘されている
^[日本芸能実演家団体協議会伝統文化振興部[-@日本芸能実演家団体協議会伝統文化振興部2008, p.14]は邦楽の演奏会に適した会場として、400席前後の観客収容数、屏風や山台といった備品とそれを設営可能な劇場スタッフ、邦楽器や邦楽の声に合った残響などの条件をあげている。]。
国立劇場伝統芸能伝承者養成所で行われている邦楽関連の養成事業としては、歌舞伎の竹本、鳴物、長唄が挙げられるが、日本芸能実演家団体協議会伝統文化振興部[-@日本芸能実演家団体協議会伝統文化振興部2008, p.126]はこれらを歌舞伎に出演する実演家の養成を目的としたものと位置付け、邦楽の公演活動を活性化するための育成事業とはいえないと指摘している。このように、日本の伝統音楽は他の伝統芸能に比べて環境面でも人材確保の面でも対応の遅れが指摘されており、その状況は現在でもおおむね変化していない。例えば、文化庁が平成29年(2017)に文化審議会に対して行った諮問でも「現在まで守り伝えられてきた多様な文化財は、日本文化全体の豊かさの基盤。後の世代への確実な継承が必要。」と指摘する一方で、「その継承の基盤となるコミュニティ自体が脆弱化する中で、地域の文化多様性の維持・発展が脅かされつつある状況にある」と指摘されている[@文化庁2017a]。また、文化庁[-@文化庁2017]の調査では「今後、文化財の保存・活用とそれによる地域振興をさらに推進していく場合、どういった課題があると思われますか。」という問いに対して、全体の35
また、2023年には日本芸術文化振興会が行なう伝統芸能伝承者養成において、文楽の研修生がゼロという事態が発生しており、公的な伝承事業の存在が担い手の育成を保障するとは限らないことが露呈した[@田中2023]。さらには、伝統文化の拠点である国立劇場の入札不成立にともなう再整備計画の大幅な遅れなど、伝統文化を取り巻く環境は改善するどころか一層厳しい状況に陥っている。このような状況において、すべての伝統音楽文化に対して人間を介した継承の実現を訴えるのは非現実的であり、程度の差こそあれ、メディアとしての人間の不在を一定程度織り込んだ形での音楽の保存や継承を模索する必要がある。

## 人文学資料のデジタル化に向けた取り組み

日本の伝統音楽関連資料については国文学研究資料館、国立国会図書館、国立公文書館等が所蔵する資料の高精細画像の公開が進んでおり、従来アクセスの難しかった資料の画像が次々とインターネットに公開されている。このような、資料のデジタル画像化は貴重な有形資料の保存と公開の両立を実現するとともに、それ自体が資料に関する記録の作成であるという側面も持っている。このような取り組みと並行して、資料内部に書かれたコンテンツに対するアプローチも近年大きく進展しつつある。例えば、国立国会図書館は光学文字認識（OCR）を用いて国立国会図書館デジタルコレクションで公開をしている著作権保護期間満了となった図書および古典籍のデジタル画像からテキストを抽出し、対象資料の全文検索を実現している。また、くずし字で書かれた資料のデジタル翻刻に取り組むみんなで翻刻は、ボランティアで構成されたコミュニティによる人文学基盤の構築事例としての大きなインパクトゆえに、そこで展開されている作業が歴史資料の``翻刻''であることの意義に光が当たりにくくなってしまっているが、この活動における極めて重要な貢献の1つは、多くの人にとって解読不可能な資料の内容に対するアクセシビリティが活動を通して飛躍的に向上し、そこから新しい発見や資料活用の可能性が開かれていくという点にあるだろう。読めない文字で書かれた資料を活字におこす翻刻作業は文献資料を扱う研究における基礎的作業であり、原資料へのアクセスを持たない人や原資料を解読できない人々にも開かれた学術資料を構築するうえで必要不可欠である。

さらに、文字認識によって得られたテキストファイルの構造化によって、資料を利用しやすく、分析や再利用を容易にしようとする取り組みも徐々に展開されつつある。例えば、テキストの構造化を目指す国際的なプロジェクトであるTEIは、人文学が扱う多様なテキストの持つ構造と資料自体のメタデータを機械可読な形式で記述するためのガイドラインを提供している。このような共通の規格にしたがってテキストを構造化することで、テキストに含まれる情報の抽出が容易になるとともに、コンピュータの支援による異なる資料間の比較、統合、分析などが容易になる。また、同様のスキーマに従って構造化されたデータであれば、国際的なコミュニティの内部での円滑なデータ共有が可能になり、分析や可視化を目的とした研究支援ツールも一定の普遍性を持つことが期待される。

このような資料の機械可読化は楽譜を中心とする音楽関連資料においても徐々に進展しつつある。楽譜の機械可読に向けた取り組みを展開しているMEIは、五線譜を中心とする音楽資料のデジタル化に向けたガイドラインを示している。MEIは楽譜に書かれた視覚的な側面にとどまらず、その資料内部で表現された楽曲の構造や特定の記述に対する解釈など、分析的な記述を含むデータ構造を整備している。TEI同様、国際的に共有されたデータ記述の形式を整備することでデータ共有を容易にすると同時に、可視化や分析のツールを共通化し、音楽関連資料のデジタル化における研究の基盤を整備することを目指している。

本研究が扱う雅楽譜は資料の特徴として、テキストの構造化を目指すTEIと音楽資料の構造化を目指すMEIの両方に重なる特徴を持っている。すなわち、楽譜でありながらその記述には五線譜のような特別に整備された記号ではなく自然言語でも用いられる文字を用いており、文字であるにもかかわらずそこに与えられた音楽的な意味を通して演奏者に楽曲の構造や演奏の指示といった情報を提供する楽譜としての役割を果たしているのである。現状、TEIもMEIもこのようなテキストで書かれた楽譜の存在を想定したデザインにはなっていない。この2つのコミュニティは非常に強い影響関係にあるにもかかわらず、文字で書かれた楽譜という両者の専門性を足して2で割ったような存在にある資料を見落としている
^[欧米圏を中心に展開されてきたこれら2つのコミュニティにとって、この見落としはある種の必然と言っても過言ではなく、責められるものではない。西洋音楽には五線譜という極めて高い普遍性を持った音楽記述体系が存在しており、音楽の構造を書き留める手段と言語活動を書き留める手段はほとんどの場面で歴史的に切り離されてきた。もっとも、MEIはTEIから派生する形で成立したコミュニティであり、テキストとは異なる記述体系を持つ西洋音楽資料に対する最適化がその中心的な目標として掲げられていたであろうことは想像に難くない。TEIとMEIの活動によって人文学資料のデジタル化は大きく進展しており、テキストはTEI、西洋音楽はMEIというある種の役割分担は一定の成功を収めていると捉えることもできる。]。

## 人文学研究におけるコンピュータの利用

このような人文学を対象とする研究活動においてデジタル技術が適用されることによって生じる多様な課題を扱う研究領域は現在デジタル人文学として展開されている。コンピュータの登場は、人間の記録を記録し、分析する方法として、新しい方法論を持ち込んだ。初期のコンピュータは人間に代わって膨大な計算を正確に行うことを目的として軍事方面で研究開発が進んだことは有名だが、人文学への応用も第二次世界大戦終戦後の早い時期から取り組まれている。他の学問分野とは大きく異なり、人文学分野におけるコンピュータ利用はその起源を明確に示すことができる[@Hockey2004]。それは、1949年にスタートしたトマス・アクィナスとその関連著者の著作に登場する全単語のデジタル索引を作成するIndex Thomisticusである。

トマス・アクィナスの使用したすべての単語の意味の違いを整理するという途方もない博士論文の執筆に取り組んだイエズス会神父のロベルト・ブーサ
^[イタリア語の母音間のsはcasaのように有声音でも無声音でも読むことが可能であり、Busaの読みとしては、ブーザ、ブーサ、ブザ、ブサの4通りが考えられる[@宮川2021]。]
は1つの単語の分析に4年を費やした自らの経験を踏まえ、コンピュータが自らの研究に役立つことを確信し、IBM創設者のトーマス・ワトソンに支援を求めた[@TIME1956]。ブーサの提案から7年後、ブーサとIBMはこのプロジェクトをスタートさせ、トマス・アクィナスの全集に含まれる118作品とトマス・アクィナスに関連するとされる他の著者による61のテキスト、約1100万語がデジタル形式で収録された。また、収録されたすべての単語に対して形態素タグが付与され、見出し語の形でコンコーダンス
^[特定の作品や文献などにおいて用いられているすべての文字列(単語)に関して、その文字列が含まれているテキストや前後の文脈などといった位置情報に関する索引やメタデータのこと[@it用語辞典バイナリ2024].]
が作成されている
^[この成果は現在Corpus Thomisticumというプロジェクトの一部としてインターネット上に公開され誰でも自由に利用できる[@Busa2024]。]
[@Hockey2004]。テキストはパンチカードに記録され、単語の出現回数、出現箇所、出現箇所の直前と直後の6つの単語を検索することが可能になった[@TIME1956]。1人の人間が一生を費やしても終えられるか定かではない作業がコンピュータを用いることで実現したのである
^[ロベルト・ブーサの功績をたたえ、The Alliance of Digital Humanities Organizations(ADHO)は3年に一度、情報技術の人文学への応用に対する顕著な業績に対してRoberto Busa Prizeを贈呈している[@AllianceofDigitalHumanitiesOrganizations2024]。]。

テキスト処理からスタートした人文学に対するコンピュータ技術の応用は、情報学の研究成果を取り込みつつ、次第にテキストの枠を超え非文字資料へと応用されていく。しかしながら、研究に対するデジタル技術の浸透度合いは分野によって大きく異なる。先ほど例に挙げたIndex Thomisticusのようなコーパスを用いた言語学研究においてコンピュータの利用が方法論にまで深く入り込んでいるのに対して、伝統的な人文学的研究手法とデジタル技術が十分に統合されているとは言い難い分野も存在する。本研究が対象とする音楽もそのひとつである。

## 本研究の目的と意義

そこで、本論文では日本の伝統音楽である雅楽
^[雅楽という言葉は東アジア圏の広い地域に広がっており、中国や朝鮮半島においては、皇室や孔子廟の祭祀音楽の名称として用いられている。一方、日本の雅楽において中心的なレパートリーを構成しているのは、中国や朝鮮半島の儀式音楽、すなわち中国、朝鮮半島における雅楽ではなく、中国において燕楽と呼ばれた饗宴の楽舞であるといわれている[@増本1994]。]
が用いる楽譜を1つの事例として取り上げ、そのデジタル化による雅楽文化の保存と継承の可能性について検討し、具体的なデジタル化の手法としてデジタル雅楽譜(GagakuXML)の構築に取り組む。楽譜は楽曲に対する演奏者の記憶を補助するために生み出され、現在でも演奏実践の現場で参照され続けている記録の一形態である。それらの記録を適切に管理するとともに、デジタル技術を用いてその記録を機械可読な形式に変換することで、音楽文化の保存と継承に新たな可能性を提供することを目指す。当然ながら、この研究が主軸とする楽譜資料が音楽文化の記録として唯一無二の存在であるわけではなく、楽譜という記録方法そのものも、本研究によって機械可読に表現されたデジタル楽譜も、あくまでも音楽文化のごく一部をある特定の方法で表現した記録に過ぎず、人間によって媒介されてきた音楽文化そのものがデータとして保存されるわけではない。この点において本研究の限界は極めて明確である。大多数の音楽文化は人間を媒体として伝承されていくが、どれだけ技術が発達したとしてもその伝承を人間から切り離し、人間以外のメディアによって完全に置き換えることはできない。もっともこの事実は、本研究に限らず人間によって生み出された文化の記録や保存に挑むあらゆる研究に共通する現実であろう。
しかしながら、常に新しい技術や手法を取り入れながら文化財の保存と記録に挑むことの重要性はこれまでの文化財保存の歴史が示すとおりである。本研究は音楽文化の中でも、日本の伝統音楽である雅楽を具体的な検討対象として取り上げるが、その背後には文化を保存し継承するための新しい方法論の模索という、文化財保存の歴史の一環としての意義が存在するのである。

数多くの音楽資料の中から楽譜を選択するのは、日本伝統音楽の中で受け継がれてきた楽譜が、かつての音楽を研究、再現するための重要な資料としてこれまでも利用されてきたためである。もちろん、音楽、特に日本の伝統音楽のような口頭伝承を主軸とした伝承文化において、楽譜という書かれた記録はあくまでも補助的な役割を果たすにとどまっており、楽譜以外にも楽書、楽器、絵図、装束など、様々な側面から雅楽の検討が積み重ねられてきた。しかし、そんな中でも、残された楽譜がかつての音楽文化を研究し、楽曲や楽器の復曲、復興のための重要な手がかりを提供していることは間違いない。有名な事例としては、正倉院に支配文書として残された「天平琵琶譜」に基づいて芝祐靖が行った復曲事業^[雅楽における復曲事業は1966年に開場した国立劇場による委嘱事業にその多くが拠っている。特に1975年以降、普段ほとんど演じられない、もしくは廃絶した上演方法や楽曲の復元を押し出した演奏会が行われており、そこに「天平琵琶譜」の復曲も含まれている。また、80年代に入ると復元された古代の楽器を用いた公演も行われるようになり、楽曲、理論、楽器といった複数のアプローチから復元に取り組まれている[@寺内2007]。]などが挙げられるが、これも紙背文書として残された譜を起点として様々な検討が行われた結果もたらされた成果である。このように、楽譜は日本の伝統音楽を研究するうえで欠かすことのできない資料の一形態であり、そのデジタル化は日本の伝統音楽文化の保存と継承に寄与することが期待される。

したがって、文化財保存とデジタル人文学のどちらの視点に立つかによって本研究は大きく2つの視点から位置付けられることになるだろう。文化財保存の観点で見るならば、本研究は実物資料に残された記述に関する構造化デジタルテキストの構築を通して、メディアとしての人間を介さない無形文化財の新しい記録の在り方を模索する試みとして捉えることができる。伝承に様々な課題を抱え、衰退が危惧される伝統音楽文化に関連した記録をデジタル化することで、既存の記録に対するアクセシビリティを向上させるとともに、新たな研究や伝承の基盤を整備できるだろう。一方、Music Encodingの分野から見ると、これまで欧米圏において同じ人文学資料のマークアップを議論しているのにもかかわらず、別々に議論が展開されてきたテキストと楽譜の構造化という2つの分野のはざまに存在する文字を用いた記譜法の構造化に向けた方法論を示す試みとして位置づけられる。雅楽譜を対象としたデジタル楽譜を整備することで、日本の伝統音楽資料研究に対するコンピュータの利用可能性が広がると同時に、音楽情報学研究の素材として日本の伝統音楽が候補になることも期待できる。また、非西洋音楽を対象としたMusic Encodingの議論は、欧米を中心に展開されてきたMusic Encodingの取り組みになかなか反映されてこなかった楽譜文化の多様性を当該研究分野にもたらすという点においても重要な取り組みである。

## 本論文の構成

序論に続く第 [-@sec-bunkazaihogo] 章では、本研究が取り組む文化の記録が文化財保護の文脈においてどのように位置付けられているのかを文化財記録の役割について検討しながら確認する。有形・無形を問わず、文化の保護をめぐる議論においては、現状を可能な限り長く保存すると同時に現状の記録を取り続けるという必要もある。ここでは、有形・無形を問わず、過去の文化財保護における保存と記録の事例を取り上げながら、無形文化財に関する記録の役割と重要性について検討する。

第 -@sec-02 章では、無形文化財である音楽を取り巻く記録と楽譜の関係性について、西洋音楽が育んできた楽譜文化を事例として検討する。音楽文化は様々な手段によって記録されてきたが、その内容は大きく客観的記録と自己記述的記録に分類される。西洋音楽における楽譜文化は、当事者による自己記述を通して演奏家の記憶を支援するという原初の目的に端を発し、より普遍的な記述を目指して発展した結果、音楽を客観的に記述可能な水準にまでその記述内容を高めてきた。文化を記録する手段として写真、録音等も取り上げながら、西欧音楽の記録手段としての五線譜とそれを取り巻く文化がもたらした一種の異質さについて明らかにする。

第 [-@sec-notationasarecord ] 章では、本論文がデジタル化に取り組む雅楽譜を育んできた雅楽そのものについて概要を示した上で、雅楽の記録として楽譜が担ってきた役割を踏まえつつ雅楽における楽譜の文化について検討する。
雅楽は日本の伝統音楽の中でも特に長い歴史を持ち、その内部には複数のジャンル、演奏形態、楽器、記譜法が存在する。本研究はその中でも唐楽中小曲譜に含まれる篳篥、龍笛、鳳笙の譜を対象として取り上げる。また、雅楽譜の具体的なマークアップに向けて雅楽譜の記述内容について整理するとともに、楽譜資料の異なるメディアへの書き換え・置き換えという点において本研究にとって重要な先行事例である五線譜化を雅楽譜の記録事業として捉え、その成果と課題を検討し、本研究が取り組む雅楽譜の符号化の位置づけを示す。

第 [-@sec-MachineReadableSheetMusic] 章では人文学と情報技術、音楽と情報学の関わりについて整理し、楽譜の機械可読化に向けた既存の取り組みを参照しつつ、デジタル雅楽譜における情報記述の構造を提示する。
情報技術を用いた音楽関連研究は主に自動演奏、楽曲推薦、光学楽譜認識、自動採譜、楽曲生成といったトピックに取り組む情報学からのアプローチと、音楽学、音楽史学、生成批評といった人文学的なアプローチから展開されてきており、両者の間では音楽情報として必要な情報の定義や取り扱い方が大きく異なっており、現在も``機械可読な楽譜データ''と呼ばれうる対象の内部に複数のコンセプトが混在した状況が生じている。本章ではそれらを整理するとともに、音楽学をはじめとする人文学系の領域から楽譜の機械可読化に取り組んだ既存のプロジェクトに採用されている情報記述モデルを参照しつつ、「雅楽情報記述の四領域モデル」を提示する。

第 [-@sec-05] 章ではXMLを用いて構築されるデジタル雅楽譜(GagakuXML)が持つ具体的な構造について示す。XMLの基本的な構造について触れたうえで、第3章で示した雅楽譜の特徴をXML上で再現するとともに、雅楽情報記述の四領域モデルの核となる半構造化譜字ユニットとメタデータの記述について具体的な構造を示す。また、作成したGagakuXMLを使用した簡易的な分析を示すとともに、デジタル雅楽譜を利用したさらなる資料の接続についてその可能性を示す。

結論では、本研究の成果と課題についてまとめ、今後の展望について述べる。
