project:
  type: book

book:
  title: "楽譜記述の機械可読化による無形文化財の保護・継承・研究"
  subtitle: "唐楽中小曲に含まれる三管の譜を対象としたデジタル版雅楽譜の構築を通して"
  author: "関慎太朗"
  language: "ja"
  date: "2025-10-7"
  date-format: "2025-10-16"
  abstract: "本書は，雅楽における楽譜の記述を機械可読化することで，雅楽に関する資料の保護・継承・研究に資することを目的としている．そのために，まず雅楽とその楽譜が持つ特徴を整理し，それらの特徴を踏まえたデジタル雅楽譜の構築に向け，西洋音楽を中心として議論されてきた音楽情報の記述モデルの整理を行う．次に，これらの知見を基盤として，雅楽とその楽譜が持つ特徴を反映したデジタル雅楽譜の情報記述モデルを提案し，そのモデルに基づいて宮内庁書陵部所蔵の『雅樂譜』に含まれる唐楽中小曲のうち三管（笙・篳篥・龍笛）に関する譜を対象としてマークアップを実践する．最後に，マークアップされたデジタル雅楽譜を用いた資料の利活用方法について考察し，今後の展望について述べる．"

  chapters:
    - index.qmd
    - chapter0.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - chapter4.qmd
    - chapter5.qmd
    - chapter6.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand

include-in-header:
  - text: |
        <script src="https://jtab.tardate.com/javascripts/jquery.js" type="text/javascript"></script>
        <script src="https://jtab.tardate.com/javascripts/raphael.js" type="text/javascript"></script>
        <script src="https://jtab.tardate.com/javascripts/jtab.js" type="text/javascript"></script>
        <link type="text/css" rel="stylesheet" href="https://jtab.tardate.com/css/jtab-helper.css"/>
        <script src="src/ruby_enabler2.js"></script>
        <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css2?family=Noto+Music&family=Noto+Sans" type="text/css"/>

format:
  html:
    header-includes: |
            <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css2?family=Noto+Music&family=Noto+Sans" type="text/css"/>
    theme:
      light: cosmo
      dark: cyborg
    

    mainfont: Noto Music,sans-serif
    toc: true
    toc-location: right
    toc-expand: true








